version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:Prasanna@1985@db:5432/studentSpace?schema=public
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Prasanna@1985
      POSTGRES_DB: studentSpace
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
